# Настройки скрытия сообщений
disable-join-message: true      # Скрывает сообщение о входе игрока
disable-quit-message: true      # Скрывает сообщение о выходе игрока
disable-death-message: true     # Скрывает сообщение о смерти игрока

# Настройки достижений
disable-advancement: true        # Полностью отключает получение достижений
disable-advancement-message: true # Отключает сообщение о получении достижения в чате
# Более надежный способ: полностью сбрасывает все достижения игроку при каждом входе. Рекомендуется оставить true.
disable-all-advancements: true

# Настройки возрождения
# Включить автоматическое возрождение без экрана смерти
auto-respawn: true

#Мой ТГК: https://t.me/Kav16Dev